### ISSUE TITLE
Unexpected behavior when using `mapped` with `view`

### ISSUE THREAD

**Issue by Koleok** [ramda/ramda-lens#10]
After reading the article and the tests, i can see `mapped` working as i would expect for `set` and `over`, but when i try it with `view` i get some odd behavior. Lets say i have the below users array like in the tests

``` javascript
const users = [{
    id: 1,
    name: 'Ivan',
    addresses: [{ street: '92 Oak St.', zip: '08081' }],
  }, {
    id: 2,
    name: 'Donielle',
    addresses: [{ street: '393 Post Ave.', zip: '93011' }],
  }, {
    id: 3,
    name: 'Rick',
    addresses: [],
}]
```

and i use `view` to get the zips like so

``` javascript
const zips = compose(mapped, addresses, mapped, zip)
view(zips, users)
```

I would expect this to act like:

``` javascript
compose(map(pluck('zip')), pluck('addresses'))

// and give me the zips like 
[["08081"], ["93011"], []]
```

but instead i get back 

``` javascript
{ id: 1, name: 'Ivan', addresses: [ [ '08081' ] ] }
```

which is closer to what i would get with

``` javascript
map(over(lensProp('addresses'), pluck('zip')))
```

**Comment by Koleok** [comment]
Here is a [repl](http://goo.gl/Z8vaXD) with the above code

**Comment by scott-christopher** [comment]
Unfortunately `mapped` can only be used to update a target, rather than view it as there is no generic way to extract a value from a functor (i.e. how would you extract the functor value from `Nothing` or `Const`?).

The Haskell `lens` library has a whole class dedicated to optics such as `mapped` called `Setter`: https://hackage.haskell.org/package/lens-4.14/docs/Control-Lens-Setter.html.

For this particular use case however, you may be interested in `traversed` instead.

``` js
const zips = compose(traversed, lensProp('addresses'), traversed, lensProp('zip'))
```

We can then use it to update the focus using `over`:

``` js
over(zips, z => `ZIP: ${z}`, users)
/*
[{
    "id":        1,
    "name":      "Ivan",
    "addresses": [{
        "street": "92 Oak St.",
        "zip":    "ZIP: 08081"
    }]
}, {
    "id":        2,
    "name":      "Donielle",
    "addresses": [{
        "street": "393 Post Ave.",
        "zip":    "ZIP: 93011"
    }]
}, {
    "id":        3,
    "name":      "Rick",
    "addresses": []
}]
*/
```

However `view` still behaves a little unnexpectedly:

``` js
view(zips, users) // "08081"
```

The behaviour you see here is due to the fact that `view` can only return a single value but we've given it a lens with multiple targets, so it defaults to returning the first value. This is slightly different from the Haskell `lens` library which requires a lens with multiple targets to focus on a monoid (something that can be `concat`ed in FantasyLand terminology) when used with `view`.

We can however make use of `foldMapOf` to extract the multiple targets into a list.

``` js
const listOf = (l, xs) => foldMapOf(l, [], x => [x], xs)
listOf(zips, users) // ["08081", "93011"]
```

I think `listOf` would be a useful inclusion to the library, so I'll raise a PR shortly.

Hope that helps. :)

**Comment by Koleok** [comment]
Immensely helpful thanks much @scott-christopher

**Comment by scott-christopher** [comment]
I've raised #12 for the inclusion of `listOf`.
