### ISSUE TITLE
Alternative to misuse of Iso

### ISSUE THREAD

**Issue by JAForbes** [ramda/ramda-lens#17]
Apologies if this is the wrong place to field this question, if someone could redirect me to a better resource that would be great!

#### Scenario
Say you want to bind a HTML `oninput[type=number]` `event.currentTarget.value` to a numeric field in a data store.  We could use lenses to write to the correct property.  But the property will be written as a string because `event.currentTarget.value` is always a string.

We could handle the data transformation in the click handler, but that could be problematic because view's are leaf nodes in the context of an application.  And if we could force the lens itself to handle the number conversion, the view could be ignorant of the requirements of the backend store.

#### Solution that misuses iso

I've gotten around this by misusing `L.iso`:

```
var valueLens = propLens('count')
  
// this is the misuse, because this isn't isomorphic
var numberLens = ramdaLens.iso(Number, Number)

var count = compose(valueLens, numberLens)

// later in the view
function oninput(e){
  R.set( count, e.currentTarget.value, stateTree )
}
```

This works perfectly, but I'd rather not abuse Lenses, or Iso's.  Is there an alternative, or a precedent I can be referred to.

Thank you so much for your time.

**Comment by scott-christopher** [comment]
If you were to change what you have to `iso(String, Number)` rather than `iso(Number, Number)` you could get the behaviour you're after while keeping the types and iso laws more or less happy.
```js
const numberLens = compose(lensProp('x'), iso(String, Number));
set(numberLens, '333', { x: 123 }); //=> { x: 333 }
```
Strictly speaking this is still partial, as it doesn't allow you to get the original string back if `Number(str)` would result in `NaN`, however this (as far as I can tell) shouldn't be an issue for your use case.

**Comment by JAForbes** [comment]
Thanks @scott-christopher , that works!  I thought I tried exactly that but when I used `over(numberLens, R.add(1), state)` it resulted in `NaN`, maybe I had the iso order back to front.  In any case, thank you!

**Comment by JAForbes** [comment]
Wait, it works with `R.add` but not with `x => x + 1`

```js
var validIso = ramdaLens.iso(String, Number)
var invalidIso = ramdaLens.iso(Number, Number)
var increment = x => x + 1
var state = { x: 123 }
R.over(validIso, increment, state); //=> { x: 1231 }

R.over(invalidIso, increment, state); //=> { x: 124 } 
```

I think `iso(String,Number)` only works with `R.add` because ramda casts the values to numbers

```js
module.exports = _curry2(function add(a, b) {
  return Number(a) + Number(b);
});
```
https://github.com/ramda/ramda/blob/v0.23.0/src/add.js#L22

`set` works though so I'm probably just misunderstanding `over`

**Comment by scott-christopher** [comment]
This is due to the focused value being treated as a string and then the function given to `over` is being applied.

e.g. you can think of `R.compose(R.lensProp('x'), iso(String, Number))` as a lens that says first grab the value at property `x`, then treat the number at that property as a string. Once this value is obtained, `over` will apply the function to the string value, then start going back the other way to rebuild the full structure, so converting it back from a string to a number, then updating the `x` property of the original object.

As you've discovered, this will work when using `set(numberLens, '333', state)` because we're giving it a string that can be converted to a number by the iso (effectively the same as performing `over(numberLens, R.always('333'), state)`).

**Comment by JAForbes** [comment]
Okay that makes sense.  Thanks for your help @scott-christopher 👍
